global:
  resolve_timeout: 5m

templates:
  - '/etc/alertmanager/telegram_template.tmpl'

route:
  receiver: telegram
  group_by: ['alertname', 'instance']
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 30m

receivers:
  - name: telegram
    telegram_configs:
      - api_url: https://api.telegram.org
        bot_token: <TOKEN>
        chat_id: <CHAT_ID>
        message_thread_id: <TOPIC_ID>
        parse_mode: 'Markdown'
        message: '{{ template "telegram.default.message" . }}'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']
